### ISSUE TITLE
Coding NPC chat functions

### ISSUE THREAD

**Issue by ZachariCooper** [UoSGamesGroups/first-semester-l4-5-group-18#10]
Need to create a script for which NPC is going to enter the room next, and what each choice is going to lead to when you talk to them.

This task will take 2 hours.

**Comment by ZachariCooper** [comment]
This task is due Sunday 30th October

**Comment by DannyJamieson** [comment]
2 hours of work has been completed. We just need to add either some Prefabs or change the code to text.
