### ISSUE TITLE
Animal Movement and Sprites

### ISSUE THREAD

**Issue by ZachariCooper** [UoSGamesGroups/first-semester-l4-5-group-18#45]
This is the task to complete where the animals will move across the screen and then they will be mirrored on the other side next to the player character where they will stay until all the animals move across with them.

This Task will be 2 Hours 
To be finished on Sunday

**Comment by DannyJamieson** [comment]
I spent 30 mins attempting to solve this issue, but have been unsuccessful. The group have agreed to ask Chris for help in out Wednesday meeting,
