### ISSUE TITLE
Playtesting

### ISSUE THREAD

**Issue by ZachariCooper** [UoSGamesGroups/first-semester-l4-5-group-18#48]
This task is to take the game that we have created and give the game to a bunch of your friends or family and read their responses to the games and note down what they are saying, what they enjoyed and disliked.

This should be in for this Monday, however isnt major until we look at it together for Wednesday and analyse the data.
This task should take 2 hours.

**Comment by ZachariCooper** [comment]
Unable to playtest due to the game being broken in the files.

Pushed back.

**Comment by DannyJamieson** [comment]
The task is reset as the game build will be build will be in a playable state. Amy and Tom, you have 6 Hours. Zak and I have 3 hours. This is due on Monday Evening.

**Comment by ZachariCooper** [comment]
This task has 3 hours for the following week until the final week.

Please get this done ASAP.
