### ISSUE TITLE
Tutorial : Arrows and Text

### ISSUE THREAD

**Issue by ZachariCooper** [UoSGamesGroups/first-semester-l4-5-group-18#51]
For the Tutorial we are going to need a universal Arrow design that needs to be fairly bold but not taking up to much of the screen, holding a similar colour scheme to the rest of the game, preferably the baby blue colour. Then to accompany this with appropriately sized text describing each of the gameplay element.
- The Player Character
- Other animals
- Items along the top
- Text box at the bottom
- Comfort bar
- The comfort buttons
- The Lightning strikes

This task will take 4 Hours
Due Monday
Dependant on Zachari Cooper task - Create design Document for the tutorial and layout design

**Comment by ThatGingerJust** [comment]
time spent: 4 hours
