### ISSUE TITLE
Environmental sounds

### ISSUE THREAD

**Issue by ZachariCooper** [UoSGamesGroups/first-semester-l4-5-group-18#6]
Creating the sounds for -
- Faint raining (Indoors)
- Thunder in the distance
- Mildly Windy.wav

This task is 3 hours.

**Comment by ZachariCooper** [comment]
This task is due Monday the 31st October

**Comment by DannyJamieson** [comment]
Spent 2 hours so far finding the needed sounds. I will cut down the thunder sound over the weekend

**Comment by DannyJamieson** [comment]
Spent 1 hour finding the last clip and changing parts in audacity.
